apiVersion: v1
kind: Service
metadata:
  name: products-db
  labels:
    name: product-db-service
    app: shop-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: product-db-pod
    app: shop-service
