version: '3'
services:
  product_api:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    ports: 
      - "8003:8003"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - default
      - shopnet

  db_reset:
    build:
      context: .
    command: python reset_db.py
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db
    
  db:
    image: mysql
    container_name: products_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

networks:
  shopnet:
    external: true
