apiVersion: v1
kind: Pod
metadata:
  name: user-api-pod
  labels:
    app: shop-service
    name: user-api-pod
spec:
  containers:
    - name: user-api
      image: user
      ports:
        - containerPort: 8000
      env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: SECRET_KEY
          value: "Strong_Secret_Key1!"
      command: ["uvicorn"]
      args: ["main:app", "--host", "0.0.0.0"]

      imagePullPolicy: Never
  automountServiceAccountToken: false
