version: '3'
services:
  tests:
    build:
      context: .
    command: pytest

  user_api:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports: 
      - "8001:8001"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - SECRET_KEY=Strong_Secret_Key1!
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - default
      - shopnet
    
  db:
    image: mysql
    container_name: users_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

networks:
  shopnet:
    external: true
