apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30005
  selector:
    app: shop-service
    name: customer-api-pod
