version: '3'
services:
  customer_api:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports: 
      - "8002:8002"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - default
      - shopnet

  db_reset:
    build:
      context: .
    command: python reset_db.py
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql
    container_name: customers_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customers
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3308:3306"

volumes:
  mysql:
  mysql_config:

networks:
  shopnet:
    external: true
