apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30006
  selector:
    app: shop-service
    name: order-api-pod
