version: '3'
services:
  order_api:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8004
    ports: 
      - "8004:8004"
    volumes:
      - ./:/app
    networks:
      - default
      - shopnet

networks:
  shopnet:
    external: true
